---
apiVersion: v2
appVersion: 2.0.18
description: Eclipse Mosquitto - An open source MQTT broker
name: mosquitto
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - mosquitto
  - MQTT
  - eclipse-iot
home: https://github.com/hdubel94/charts/tree/master/charts/stable/mosquitto
icon: https://raw.githubusercontent.com/eclipse/mosquitto/master/logo/mosquitto-logo-min.svg
sources:
  - https://github.com/eclipse/mosquitto
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://hdubel94.github.io/library-charts/
    version: 1.0.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.0.0
