#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

tolerations:
  - key: hardware
    operator: Equal
    value: nvidia-jetson
    effect: NoSchedule

nodeSelector:
  hardware: "nvidia-jetson"

image:
  # -- image repository
  repository: lscr.io/linuxserver/prowlarr
  # @default -- chart.appVersion
  tag: 1.13.3
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/New_York

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9696

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: "prowlarr.crimsyn.local"
        paths:
          - path: /
            pathType: Prefix

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
  plex:
    enabled: true
    storageClass: nfs-plex
    accessMode: ReadWriteMany
    mountPath: /data/media
  downloads:
    enabled: true
    type: hostPath
    hostPath: /data/torrents
    mountPath: /data/torrents


